services: 
  # 서비스 명
  postgresql:
    # 사용할 이미지
    image: postgres
    # 컨테이너 실행 시 재시작
    restart: always
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "${DB_PORT}:5432"
    # 환경 변수 설정
    environment:
      POSTGRES_DB: account
      # PostgreSQL 계정 및 패스워드 설정 옵션
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    # 볼륨 설정
    volumes:
      - ./volume/postgres/:/var/lib/postgresql/data